<html>

<body>
    <!-- 查看父元素，可以看到下面有一片空白的占据了位置但是无内容 -->
    <!-- 将style代码中的height不注释后会发现空白位置消失，说明是滚动条占据了位置 -->

    <div style="background: #999999;padding:20px;width:300px;display: -webkit-box;overflow: scroll;">
        <div style="background: blue;width:300px"></div>
        <div style="background: green;width:400px">2</div>
        <div style="background: greenyellow;width:500px">3</div>
        <div style="background: red;width:100px">4</div>
        <div style="background: green;width:200px">5</div>
        <div style="background: red;width:400px">6</div>


    </div>
</body>
<script>
    //case1：同时有then的第二个参数和catch--谁在前面执行谁
    //情况1：then在前面
    // new Promise((resolve, reject) => {
    //     reject('拒绝了啊')
    // }).then(() => { }, (err) => {
    //     console.error('then中', err)
    // }).catch((err) => {
    //     console.error('catch中', err)
    // })

    //情况2：catch在前面
    // new Promise((resolve, reject) => {
    //     reject('拒绝了啊')
    // }).catch((err) => {
    //     console.error('catch中', err)
    // }).then(() => { }, (err) => {
    //     console.error('then中', err)
    // })


    //情况3：
    //then中抛异常，catch可以捕获到
    // new Promise((resolve, reject) => {
    //     reject('拒绝了啊')
    // }).then(() => { }, (err) => {
    //     console.error('then中', err)
    //     throw new Error('then中抛异常')
    // }).catch((err) => {
    //     console.error('catch中', err)
    // })

    //情况3：
    //catch中抛异常，then可以捕获到
    new Promise((resolve, reject) => {
        resolve('拒绝了啊')
    }).catch((err) => {
        console.error('catch中', err)
        throw new Error('then中抛异常')

    }).then(() => { }, (err) => {
        console.error('then中', err)
    })


</script>
<style>
    body {
        margin: 0;
        padding: 0
    }

    ::-webkit-scrollbar {
        width: 0px;
        /* height: 0px; */
    }
</style>

</html>